language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
  - export CXX="g++-4.8" CC="gcc-4.8"
  - make dist
notifications:
  email:
    recipients:
    - ivan@esp8266.com
    on_success: change
    on_failure: always
deploy:
  provider: releases
  api_key:
    secure: Lg/Po5YFRcnrpqjgrdHcyGdxhRe8iB01Og8hvTmhhDxew1mpVHCfcZxO1VMpBxWnLS3ud4UdMjC3RBpcCWTvt0w9g35Vt9cj7XgnBEBHrBBA5DL+E5cAj/5Sf63pztc85m/kB0WODNG2NQiTpjonszrFHpmWdmXp3mqP95mZVBw=
  file: mkspiffs-$TRAVIS_TAG-linux64.tar.gz
  on:
    repo: igrr/mkspiffs
    tags: true
    all_branches: true
