version: 0.0.{build}

platform:
    - x86

skip_commits:
  message: /\[ci skip\]/

matrix:
    fast_finish: true

build_script:
    - SET PATH=C:\MinGW\bin;C:\MinGW\msys\1.0\bin;%PATH%
    - make dist

artifacts:
  - path: '*.zip'

deploy:
    release: $(PRODUCT_VERSION)
    provider: GitHub
    auth_token:
        secure: 'exejPglIPIQteWFNOUBqPhMxVjA84wktH0xF4rI/IVcsD9UG0Wc/M/xzIl/sie9h'
    artifact: /.*\.zip/
    draft: true
    prerelease: false
    on:
        appveyor_repo_tag: true
